name: package-builder
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install poetry
          python -m poetry install
      - name: Build
        run: |
          python -m poetry run pyinstaller main.py --clean -F
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ira-win-${{ steps.date.outputs.date }}
          path: dist/main.exe
